"""Interactive terminal wizard for guided publication conversion.

Provides step-by-step interactive configuration in the terminal for
selecting publications, choosing output structures (modular libraries or single documents),
configuring parsing profiles, setting destination directories, and optional
AI structure review.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from mdook.core.scanner import DiscoveredBook, scan_directory

SUPPORTED_EXTENSIONS = {".pdf", ".epub", ".docx"}


@dataclass
class WizardConfig:
    """Resolved configuration generated by the interactive wizard."""

    books: list[Path]
    output_dir: Path
    profile: str = "auto"
    single_file: bool = False
    ai_enabled: bool = False
    ai_model: str | None = None
    ai_base_url: str | None = None
    ai_api_key: str | None = None


def parse_selection(
    selection_str: str,
    available_books: list[DiscoveredBook],
) -> list[Path]:
    """Parses selection string into list of publication Paths.

    Supports:
    - 'all' or '*' for all discovered publications
    - single indices: '1'
    - comma-separated: '1, 3, 5'
    - ranges: '1-3'
    - mix of ranges and indices: '1, 3-5'
    - direct file path: 'path/to/book.pdf'
    """
    raw = selection_str.strip()
    if not raw:
        raise ValueError("Selection cannot be empty.")

    # Direct file path check
    direct_path = Path(raw).expanduser()
    if direct_path.is_file() and direct_path.suffix.lower() in SUPPORTED_EXTENSIONS:
        return [direct_path.resolve()]

    if raw.lower() in ("all", "*"):
        if not available_books:
            raise ValueError("No discovered publications available to select 'all'.")
        return [b.path for b in available_books]

    selected_indices: set[int] = set()
    parts = [p.strip() for p in raw.split(",") if p.strip()]

    for part in parts:
        if "-" in part:
            range_tokens = [t.strip() for t in part.split("-", 1)]
            if len(range_tokens) == 2 and range_tokens[0].isdigit() and range_tokens[1].isdigit():
                start, end = int(range_tokens[0]), int(range_tokens[1])
                if start > end:
                    start, end = end, start
                for idx in range(start, end + 1):
                    selected_indices.add(idx)
            else:
                raise ValueError(f"Invalid range expression: '{part}'")
        elif part.isdigit():
            selected_indices.add(int(part))
        else:
            # Check if part is a single custom file path
            candidate = Path(part).expanduser()
            if candidate.is_file() and candidate.suffix.lower() in SUPPORTED_EXTENSIONS:
                return [candidate.resolve()]
            raise ValueError(f"Unrecognized selection or file not found: '{part}'")

    if not selected_indices:
        raise ValueError("No valid publication indices selected.")

    resolved_paths: list[Path] = []
    book_count = len(available_books)

    for idx in sorted(selected_indices):
        if 1 <= idx <= book_count:
            resolved_paths.append(available_books[idx - 1].path)
        else:
            raise ValueError(
                f"Index {idx} is out of range. Available options: 1 to {book_count}."
            )

    return resolved_paths


def _prompt_user(
    prompt_text: str,
    default: str | None = None,
    console: Console | None = None,
    input_fn: Callable[[str], str] | None = None,
) -> str:
    """Prompts the user for text input with optional default and fallback."""
    c = console or Console()
    if default is not None:
        full_prompt = f"{prompt_text} [{default}]: "
    else:
        full_prompt = f"{prompt_text}: "

    if input_fn is not None:
        c.print(full_prompt, end="")
        user_val = input_fn(full_prompt).strip()
        c.print(user_val)  # Echo back for console recording / visibility
    else:
        user_val = c.input(full_prompt).strip()

    if not user_val and default is not None:
        return default
    return user_val


def interactive_wizard(
    console: Console | None = None,
    start_dir: Path | None = None,
    input_fn: Callable[[str], str] | None = None,
) -> WizardConfig | None:
    """Guides the user through an interactive conversion wizard in the terminal.

    Returns:
        WizardConfig if confirmed, or None if cancelled by the user.
    """
    c = console or Console()
    scan_path = (start_dir or Path(".")).expanduser().resolve()

    c.print()
    c.print(
        Panel.fit(
            "[bold white]Mdook Interactive Wizard[/bold white]\n"
            "[dim]Guided conversion of publications into structured Markdown libraries[/dim]",
            border_style="cyan",
            box=box.ROUNDED,
        )
    )
    c.print()

    # Step 1: Scan & Publication Selection
    try:
        discovered = scan_directory(scan_path, recursive=False)
    except Exception:
        discovered = []

    selected_books: list[Path] = []
    if discovered:
        title_target = scan_path.name or str(scan_path)
        table = Table(
            title=f"Discovered Publications in {title_target} ({len(discovered)})",
            box=box.ROUNDED,
            header_style="bold cyan",
            border_style="dim",
            show_lines=False,
        )
        table.add_column("#", justify="right", style="dim", width=4)
        table.add_column("Format", justify="center", width=8)
        table.add_column("Filename", style="bold white")
        table.add_column("Size", justify="right", style="dim", width=10)
        table.add_column("Title", style="italic")

        format_styles = {
            "pdf": "[bold red]PDF[/bold red]",
            "epub": "[bold green]EPUB[/bold green]",
            "docx": "[bold blue]DOCX[/bold blue]",
        }

        for idx, b in enumerate(discovered, 1):
            fmt_badge = format_styles.get(b.format.lower(), b.format.upper())
            table.add_row(str(idx), fmt_badge, b.filename, b.formatted_size, b.title)

        c.print(table)
        c.print()

        while not selected_books:
            default_sel = "1" if len(discovered) == 1 else "all"
            user_input = _prompt_user(
                "Select publications to convert (e.g. 1, 1-3, all, or custom file path)",
                default=default_sel,
                console=c,
                input_fn=input_fn,
            )
            try:
                selected_books = parse_selection(user_input, discovered)
            except ValueError as err:
                c.print(f"[bold red]Error:[/bold red] {err}")
    else:
        c.print(
            f"[dim]No supported publications found in [bold]{scan_path}[/bold].[/dim]"
        )
        while not selected_books:
            path_input = _prompt_user(
                "Enter path to publication file (.pdf, .epub, .docx)",
                console=c,
                input_fn=input_fn,
            )
            p = Path(path_input).expanduser()
            if not p.exists():
                c.print(f"[bold red]Error:[/bold red] File not found: '{p}'")
                continue
            if not p.is_file() or p.suffix.lower() not in SUPPORTED_EXTENSIONS:
                c.print(
                    f"[bold red]Error:[/bold red] Unsupported format: '{p.name}'. "
                    f"Supported formats: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
                )
                continue
            selected_books = [p.resolve()]

    c.print(
        f"[green]Selected:[/green] {len(selected_books)} publication(s): "
        f"{', '.join(p.name for p in selected_books)}"
    )
    c.print()

    # Step 2: Output Structure Mode
    c.print("[bold cyan]Output Structure Mode:[/bold cyan]")
    c.print("  [1] Modular Library (Chapter-split Markdown files)")
    c.print("  [2] Single Document (Single continuous Markdown file)")
    mode_choice = _prompt_user("Select mode", default="1", console=c, input_fn=input_fn)
    single_file = mode_choice.strip() == "2"
    mode_label = "Single Document" if single_file else "Modular Library"
    c.print(f"[green]Mode:[/green] {mode_label}")
    c.print()

    # Step 3: Parsing Profile
    c.print("[bold cyan]Semantic Parsing Profile:[/bold cyan]")
    c.print("  [1] Auto-Detect (Document typography determines extraction profile)")
    c.print("  [2] Literature (Optimized for narrative prose, fiction, and essays)")
    c.print("  [3] Technical (Optimized for code blocks, formulas, tables, and academic papers)")
    profile_choice = _prompt_user(
        "Select profile", default="1", console=c, input_fn=input_fn
    )
    profile_map = {"1": "auto", "2": "literature", "3": "technical"}
    profile = profile_map.get(profile_choice.strip(), "auto")
    c.print(f"[green]Profile:[/green] {profile}")
    c.print()

    # Step 4: Destination Directory
    dest_input = _prompt_user(
        "Destination directory", default="./output", console=c, input_fn=input_fn
    )
    output_dir = Path(dest_input).expanduser().resolve()
    c.print(f"[green]Destination:[/green] {output_dir}")
    c.print()

    # Step 5: AI Structure Review
    ai_prompt = _prompt_user(
        "Enable AI structure review? [y/N]",
        default="n",
        console=c,
        input_fn=input_fn,
    )
    ai_enabled = ai_prompt.lower() in ("y", "yes", "true", "1")

    ai_model: str | None = None
    ai_base_url: str | None = None
    ai_api_key: str | None = None

    if ai_enabled:
        c.print()
        c.print("[bold cyan]AI Review Provider:[/bold cyan]")
        c.print("  [1] Local / Ollama (http://localhost:11434/v1, llama3.2)")
        c.print("  [2] OpenRouter / Custom OpenAI-compatible endpoint")
        provider_choice = _prompt_user(
            "Select provider", default="1", console=c, input_fn=input_fn
        )
        if provider_choice.strip() == "2":
            default_base_url = os.environ.get(
                "MDOOK_LLM_BASE_URL",
                os.environ.get("OPENAI_BASE_URL", "https://openrouter.ai/api/v1"),
            )
            ai_base_url = _prompt_user(
                "Base URL", default=default_base_url, console=c, input_fn=input_fn
            )
            default_model = os.environ.get(
                "MDOOK_LLM_MODEL", "anthropic/claude-3.5-haiku"
            )
            ai_model = _prompt_user(
                "Model name", default=default_model, console=c, input_fn=input_fn
            )
            default_key = os.environ.get(
                "MDOOK_LLM_API_KEY", os.environ.get("OPENAI_API_KEY", "")
            )
            key_prompt = _prompt_user(
                "API key",
                default=default_key if default_key else "none",
                console=c,
                input_fn=input_fn,
            )
            ai_api_key = None if key_prompt.lower() == "none" else key_prompt
        else:
            ai_base_url = "http://localhost:11434/v1"
            ai_model = _prompt_user(
                "Ollama model name", default="llama3.2", console=c, input_fn=input_fn
            )
            ai_api_key = "ollama"

        c.print(f"[green]AI Review:[/green] Enabled ({ai_model} via {ai_base_url})")
    else:
        c.print("[dim]AI Review: Disabled[/dim]")

    c.print()

    # Step 6: Pre-flight Summary & Confirmation
    summary_table = Table(
        title="Pre-Flight Conversion Summary",
        box=box.ROUNDED,
        header_style="bold cyan",
        border_style="cyan",
        show_lines=True,
    )
    summary_table.add_column("Setting", style="bold white", width=22)
    summary_table.add_column("Value", style="cyan")

    book_names = ", ".join(b.name for b in selected_books)
    summary_table.add_row("Publications", f"{len(selected_books)} file(s) ({book_names})")
    summary_table.add_row("Output Structure", mode_label)
    summary_table.add_row("Parsing Profile", profile)
    summary_table.add_row("Destination", str(output_dir))
    ai_desc = (
        f"Enabled ({ai_model} at {ai_base_url})"
        if ai_enabled
        else "Disabled"
    )
    summary_table.add_row("AI Review", ai_desc)

    c.print(summary_table)
    c.print()

    confirm = _prompt_user(
        "Proceed with conversion? [Y/n]",
        default="y",
        console=c,
        input_fn=input_fn,
    )
    if confirm.lower() not in ("y", "yes", ""):
        c.print("[yellow]Conversion cancelled.[/yellow]")
        return None

    return WizardConfig(
        books=selected_books,
        output_dir=output_dir,
        profile=profile,
        single_file=single_file,
        ai_enabled=ai_enabled,
        ai_model=ai_model,
        ai_base_url=ai_base_url,
        ai_api_key=ai_api_key,
    )
